### ISSUE TITLE
[CCK 4 MEGATHREAD] New Control Panel, Build Pipeline, and Localization System

### ISSUE THREAD

**Issue by NotAKidoS** [ChilloutVR-Team/ChilloutVR-Issues#1833]
Report any issues you run into here with the CCK 4 preview releases. 

Suggestions or new features also welcomed, but please note that ironing things out & fixing bugs is the priority.

**Comment by Momofier** [comment]
Localization list Doesn't update automatically when you add in New Entries

**Comment by Momofier** [comment]
I say we add more Meme Localization Options like Pirate Speak and GenZ Slang

**Comment by Momofier** [comment]
When you change Localization  it reverts the Upload Region to Europe. Always.

**Comment by giwaff** [comment]
> When you change Localization it reverts the Upload Region to Europe. Always.

noticing this too!

**Comment by NotAKidoS** [comment]
> Localization list Doesn't update automatically when you add in New Entries

It only fetches when the Control Panel has been opened due to it needing to do a resources lookup on the entire project. I can see if it is possible to scan when clicking the dropdown as well prior to displaying any results.

> I say we add more Meme Localization Options like Pirate Speak and GenZ Slang

I would like to prioritize using the localization system for real languages for the officially shipped CCK. You can host the meme languages yourself though.

> I think we need to add more things to Localization 

Definitely. This was just a first pass with what I happened to wire up after introducing it to the project. I am currently going through all the CCK components with rebuilt bubbly-GUIs and running them through the localization system.

> When you change the Localization it reverts the Upload Region to Europe. Always.

The toggle is not yet wired up to store as an editor preference & changing selected locale rebuilds any listening GUI. The dropdown currently is ignored anyways by the API as we only have one upload location atm, but I will still hook it up so it "just works" when we spin up more upload locations later.

**Comment by Momofier** [comment]
<img width="1666" height="227" alt="Image" src="https://github.com/user-attachments/assets/97eee671-a78e-42dc-a215-adaa591c56a5" />
Caching issue

**Comment by Momofier** [comment]
<img width="385" height="157" alt="Image" src="https://github.com/user-attachments/assets/ff21f78a-7c4c-42ba-b233-f8273ed2afd9" />

Panoramic image isn't Generated on New Uploads. (nor is there a Generation button for Panoramic images)

**Comment by Momofier** [comment]
Newly added Animators/ animations after Initial Uploads are not Caught for Network Synced. Thus Causing some settings to not Globally sync that are set to Globally Sync

**Comment by NotAKidoS** [comment]
I don't think it necessarily matters to validate scripts which don't exist on the client. We have plenty of users who rely on scripts added to the game via mods for example.

**Comment by NotAKidoS** [comment]
> CCK 4.0's new build panel currently does not take filesystem case sensitivity into account during build/upload.

The system which caused this has been destroyed pending next preview CCK. The BundleCacheManager was a last minute addition prior to release to ensure the built outputs didn't just pile up forever like my personal panel (if you used that you probably have gigs of shit in appdata...).

The built bundles will now be stored in a temp folder which Unity clears each session. The upload process will also now delete the bundle as a final step, and local test will delete any prior bundle before the building starts.

Alongside this the image cache (primarily used by the Browser tab) has been moved to appdata/local/ so it can be shared amongst all projects on the same machine. 

The next preview CCK will automatically clean up the old Builds/ and Library/ImageCache/ directories on import if found.

**Comment by NotAKidoS** [comment]
> Panoramic image isn't Generated on New Uploads.

This has been addressed. I fucked it up because it was also a last minute adjustment to make the panoramic be taken towards the end of the content building pipeline, so actions taken by any CCKBuildAction components would be captured. My bad.

**Comment by NotAKidoS** [comment]
> Validation suggestion: weird avatar scaling/etc.

I could possibly provide a warning, but really this is a client issue. It should ideally "just work".

**Comment by NotAKidoS** [comment]
> Unable to build using legacy builder on Linux

This was not specific to Linux & was addressed in the latest preview cck release.

**Comment by NotAKidoS** [comment]
> I think we need more things added to Localization

I ran a bunch of components and the tabs through the localization system & set them up for the shipped owo language. There are still specific strings, mostly on highly specific UI elements, that still need adjustment, but I will await further feedback before diving into them.

**Comment by hanetzer** [comment]
> I don't think it necessarily matters to validate scripts which don't exist on the client. We have plenty of users who rely on scripts added to the game via mods for example.

I more mean scripts which will *never* be part of the client. Aka, vrchat related ones for now. I'm not aware of any other 'normal unity' social vr game.


> > CCK 4.0's new build panel currently does not take filesystem case sensitivity into account during build/upload.
> 
> The system which caused this has been destroyed pending next preview CCK. The BundleCacheManager was a last minute addition prior to release to ensure the built outputs didn't just pile up forever like my personal panel (if you used that you probably have gigs of shit in appdata...).
> 
> The built bundles will now be stored in a temp folder which Unity clears each session. The upload process will also now delete the bundle as a final step, and local test will delete any prior bundle before the building starts.
> 
> Alongside this the image cache (primarily used by the Browser tab) has been moved to appdata/local/ so it can be shared amongst all projects on the same machine.
> 
> The next preview CCK will automatically clean up the old Builds/ and Library/ImageCache/ directories on import if found.

If its still using the same code path to determine the filename for cvravatar creation and CVRAvatar uploading it will still fail on anything but windows. I'd highly suggest enforcing all lowercase for all files involved in the process.

**Comment by NotAKidoS** [comment]
> If its still using the same code path to determine the filename for cvravatar creation and CVRAvatar uploading it will still fail on anything but windows. I'd highly suggest enforcing all lowercase for all files involved in the process.

Just double checked and it seems the resulting file Unity builds when building an asset bundle is all lowercase. The build pipeline already passed the built bundle path throughout the build steps without reconstructing it, (except the BundleCacheManager which is now gone), so it would have worked fine had the output Unity gave respected my casing I passed to BuildAssetBundles.

I'll tweak the creation of the file name before next preview release to ensure it's lowercase to account for this.

**Comment by NotAKidoS** [comment]
> I more mean scripts which will never be part of the client. Aka, vrchat related ones for now. I'm not aware of any other 'normal unity' social vr game.

There wouldn't be a good way to go about doing this except flagging all unknown components & requiring mod makers to "make themselves known" to the CCK.

The end result is only the scripts we ship are usable anyways, with a harmless log on content load, so I don't see it as being a needed thing.

**Comment by hanetzer** [comment]
> There wouldn't be a good way to go about doing this except flagging all unknown components & requiring mod makers to "make themselves known" to the CCK.
> 
Nah. its called a 'blacklist'; its the *exact* use case for this kind of thing.
blacklist vrchat's guids, leave everything else alone, unless another component/set of components becomes known to be an issue.

**Comment by NotAKidoS** [comment]
> Nah. it's called a 'blacklist'; it's the exact use case for this kind of thing.
blacklist vrchat's guids, leave everything else alone, unless another component/set of components becomes known to be an issue.

I do not believe it would provide any tangible benefit to implement a "VRC component blacklist" as a validation. The CCK also could not rely on file guids for that purpose considering there are several stub packages of their SDK out there.

While I could maybe check for the name of the assembly or prefix of the component name it just doesn't really make sense to do so. It would be adding extra processing during validation that really does not have a functional purpose in the end.

**Comment by hanetzer** [comment]
The stub vrchat packages *only work* because they use the same GUIDs tho? 😕 
just like the db stubs package only works because it uses the same GUIDs and data structures.

**Comment by NotAKidoS** [comment]
> The stub vrchat packages only work because they use the same GUIDs tho?

~~No, they work by being the same assembly/namespace/type with the same serialized fields. The file guids matter none.~~

You can try it by duplicating a cs script in Unity. It will fail compilation because of conflicting types.

Edit:
Actually I am wrong. The file guids matter for deserialization of existing component references within prefabs/scenes. If you are just compiling against them though their file guids do not matter.

**Comment by hanetzer** [comment]
Sure. But the entire point of the vrchat and db stubs is *exactly that*, serdes on data of those types without the whole package. The reason I'm suggesting this is I've seen a few cases where existing avatars in cvr have vrchat components on them and they just *spam* the log for every vrcavatar/vrcpipeline/physbone/contact/whatever. Sure its only for a bit during avatar instantiation but it would be trivial enough to warn/error on it, or even add a 'nuke vrchat stuff' util to the cck. we already know how to identify these components, and users of the stubs can and do make mistakes and leave the old stuff behind after conversion.

**Comment by Momofier** [comment]
Make Browser Choose a Default Category to show. I got confuzzled when it said nothing to show Despite me having all 3 Categories with stuff. Pls do something about it!! @^@

**Comment by AstroDogeDX** [comment]
## Validation gets in a cyclical loop over mip map contexts (4.0.0-Preview.6)
Textures applied to materials that are used in both supported and unsupported mip map contexts cause the validator to throw itself into a loop if you use the auto-fix option, because it'll complain about them being used in unsupported contexts -> auto fix -> complain that mip mapping isn't enabled -> auto fix -> unsup... you get the point.

Maybe ignore textures that are being used in a valid context *at least once*? An example of what is causing this is that I'm using a texture as a decal on a material - it doesn't seem to like not being mip mapped but being mip mapped apparently isn't a valid context even though it's inside a shader that is on a SkinnedMeshRenderer.

**Comment by Momofier** [comment]
Make the Unified Expressions pick up more Blendshapes by default Also Some Blendshapes for certain avatars are not Split up. This needs to be detected

Implement Common Names for ARKit, Sranipal, and Meta into detection for Unified Expressions
Implement Combined blendshape detection

Some Documentation that can be followed would be [here](https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/compatibility/overview) as many avatars use this as a guidelines and would expect these to show

<img width="1005" height="827" alt="Image" src="https://github.com/user-attachments/assets/6f32ee75-58fc-4ae7-9831-08c1feaf90ef" />

<img width="910" height="257" alt="Image" src="https://github.com/user-attachments/assets/e5c5f6ba-0dc3-411a-a781-abe66b15a9d7" />

<img width="719" height="400" alt="Image" src="https://github.com/user-attachments/assets/c9dcec48-c137-4e6b-ae4d-d5c8a32c0e37" />

<img width="883" height="233" alt="Image" src="https://github.com/user-attachments/assets/3d5c731f-c3ac-4dd6-a855-2b6ce7bbcd09" />

**Comment by NotAKidoS** [comment]
Anything about UE or Face Tracking is not specific to CCK4 or what I am working on. That is being done by SDraw.
I'd recommend making a new post regarding the changes you want for that.

As for changing how the auto-detect works, I could do that, but I'd need a full list of what you want. I don't have any experience with setting up FT personally & just do the CCK GUI when asked.

**Comment by NotAKidoS** [comment]
> Validation gets in a cyclical loop over mip map contexts (4.0.0-Preview.6)

I believe this is fixed now? Try again with the latest preview.

I am confused though- was this decal only being used on a SMR, no where else? The texture will only be detected as "unsupported mip streaming" if an instance of it is found not referenced through a material on a SMR.

**Comment by NotAKidoS** [comment]
Actually I figured it out. Materials referenced in animation clips were parsed, but not associated with the renderer they targeted. I've adjusted the scanning to override that association with the found renderer at that path.

**Comment by TikkaQrow** [comment]
Blendshape generation via Dynamic Penatration System for 'Socket' deformation causes 'false flag' streaming mip-maps issue, preventing upload.

The 'Oriface setup' allows DPS compatable shaders to drive up to 4 blendshapes on skinned mesh renderers via a .asset 'texture'
To replicate, install DPS, upload 'tube' as a prop with DPS driven deforms.

<img width="1522" height="1305" alt="Image" src="https://github.com/user-attachments/assets/0e8816c1-6097-4246-9637-e97aebef0d43" />

<img width="2055" height="1221" alt="Image" src="https://github.com/user-attachments/assets/e4d61966-d3bf-4332-b00f-d8bc3b2fc760" />

**Comment by ZeirTheFox01** [comment]
There should be a way to crop and move around the picture so that it doesn't squeeze a ful rectangle photo into a square.
And with the capture, there should be a way to preview while moving the camera before the capture is taken. (Like in the Old Panel with the Shotcam)
<img width="474" height="334" alt="Image" src="https://github.com/user-attachments/assets/eb9724fd-5ca9-4d45-92c7-924a37ab014f" />

**Comment by Momofier** [comment]
> Anything about UE or Face Tracking is not specific to CCK4 or what I am working on. That is being done by SDraw. I'd recommend making a new post regarding the changes you want for that.
> 
> As for changing how the auto-detect works, I could do that, but I'd need a full list of what you want. I don't have any experience with setting up FT personally & just do the CCK GUI when asked.

I went ahead and Reposted it as an Enhancement and the Full List would be in that Documented and I elaborated Further in the Feature enhancement post.

**Comment by SketchFoxsky** [comment]
https://github.com/ChilloutVR-Team/ChilloutVR-Issues/issues/1757

**Comment by NotAKidoS** [comment]
> #1757

this is out of scope for CCK4

**Comment by NotAKidoS** [comment]
> there should be a way to preview while moving the camera before the capture is taken

this is planned but i've placed it on the back burner for now while i iron out some other things

for cropping i am unsure... building the ui for that sounds like a pain in the ass

will see though

**Comment by VoyVivika** [comment]
It'd be nice if we could capture an image from a camera in the scene instead of only being able to capture an image from the scene view

**Comment by hanetzer** [comment]
> this is out of scope for CCK4

Tbh, I don't think it is? Weren't you thinking of implementing the UnusedBoneRefCleaner into the cck? Same idea kinda; if no manual mouth/index/etc pointers are found, do the default cvr math on the avi at build time?

**Comment by NotAKidoS** [comment]
The bone cleaner does not require client-side changes to accompany it. Everything in CCK4 so far has been editor side only, as that is what's been neglected for so long. It is the primary focus of CCK4.

Adding a method to define collider positions requires me to modify avatar load & handle both new & existing setups. It's not something i can just slap together willy nilly. I would want proper thought put into it to ensure it doesn't end up half-baked like the BodyControl & FPRExclusion features, which is time I don't want to take away from CCK4s development.

**Comment by NotAKidoS** [comment]
I also want to make specific: The new "build pipeline" in CCK4 is addressing the lackluster internal build process of content & lack of APIs to hook into it. It is not the user *workflow* being targeted specifically, which I would say the requested feature would fall under.

The one exception being made for this is the World portal panoramics due to timing of next Stable & potential issues with exposing the current upload procedure to thirdparty tools hooking the CCK. I am reworking their workflow as the upload procedure and processing was changed in a way to address several issues at once.

**Comment by NotAKidoS** [comment]
> But you don't? 

You misunderstood the requested feature then. They were asking for ways to place the autogenerated DB & MC colliders without owning the asset. This would require me to implement new options into the avatar script or a new component as well as implement it on the client. 

The CCK cannot ship stubs or generate them at build time.

**Comment by NotAKidoS** [comment]
Ideally that would be one in the same, or at least loosely related with how it's exposed or displayed in the CCK alongside the autogenerated dynamics colliders. It requires proper planning which I cannot comfortably dedicate time to considering the backlog of tasks I've written down as needing addressing for the rest of CCK4 (mostly being internal changes, fixes, or extensions of already added editor-side functionality).

**Comment by NotAKidoS** [comment]
> It *could* still do the `if (mc2 && !manual_colliders) place_mc2_default_colliders()` at build time tho. same for db.
> actually. I know MC2 places a macro/definition into the project. not sure about DB tho. So maybe doing it with db would be harder. Either way, eh.

I would not want to implement jank specific to DB/MC. If we exposed the placement of the autogenerated colliders I'd want to make it generic. 

That also still would not address the original feedback post. They want an alternative if they don't own the asset.

**Comment by hanetzer** [comment]
Noticed something. using the 4.0 preview 10 cck. if I have the avatar set up as a variant prefab with all overrides applied (so not just an fbx in the scene), and I upload it, the CVR Asset Info script on the avatar shows as modified, even tho there's no changes I can see personally.

**Comment by NotAKidoS** [comment]
Several items are stored in the asset info internally. 

- unity version
- cck version
- guid
- local editor identifier (editor only)
- content type
- random number from 111111 to 999999 (editor only)

It is likely the random number and local editor identifier being set causing unity to display that. 

The editor identifier is used for the build panel to identify content across domain reloads & provide a content id when local testing (set on cvrassetinfo enable, regen if conflict). 

The random number is so the asset bundles don't have the same name (set on both test & upload).

**Comment by hanetzer** [comment]
Ah. tbh I had an idea that something like this may be the case, but wanted to mention it at least.

**Comment by NotAKidoS** [comment]
I believe i've heard somewhere that tooling like this dirtying the prefabs on build can mess with some people's workflows, but I am personally unfamiliar as I have never explored using prefab variants for my personal content. If it is an issue I would like to know, as some things I can possibly reimplement, but wouldn't want to tackle that blind.

**Comment by NotAKidoS** [comment]
Actually I believe it was an issue in another tool I saw. The tool in question dirtied the prefabs every time its GUI would draw, which made the prefab variant workflow annoying?

It was probably something I saw hai post while ago lol.

**Comment by ZeirTheFox01** [comment]
I was told to post it here:
LTCGI doesn't work when uploading the world with the new Build Panel, but it works when uploading with the old Build Panel.

**Comment by SketchFoxsky** [comment]
Cannot local test on new build panel, works on old build panel however

**Comment by SketchFoxsky** [comment]
Local testing bundles does not check unity versions before building and launching the game!

**Comment by NotAKidoS** [comment]
> Local testing bundles does not check unity versions before building and launching the game!

not really behaviour that matters to be validated, if people want to mess around they can :shrug:

**Comment by SolacianAllie** [comment]
Auto Tagging ignores advanced tagging settings and still applies full removal tags instead of utilising advanced tags
its also reporting all audio in the project thats over the volume limit, not just whats on the avatar

**Comment by Momofier** [comment]
Animations with missing References  causes build Validations to Fail in New uploader that don't in Old. (I am still able to upload these in Old Uploader but it's still annoying.) 
<img width="894" height="1949" alt="Image" src="https://github.com/user-attachments/assets/47a909c3-6888-49ba-a201-0eefbaca8fa5" />

I tend to use the same Clip for Multiple Props/ Worlds for Speedy Uploads as I already have things setup in an Animator

I think this should be a warning rather than a compiler Error. as it prevents upload of things that would build normally

**Comment by ZeirTheFox01** [comment]
Uploading with the new CCK 4.0 panel breaks the world lighting after the upload
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/853c2bbc-a189-4aa4-8a4a-a0bc0be6683f" />
This is how the lighting normally looks like, it doesn't break when uploading with the old panel:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e4783f52-3740-4733-9fb5-4d8cf5128859" />

**Comment by Hobohan** [comment]
Encountered this error while importing LTCGI 

or maybe i did a dumb was told to post here.

`
Assets\CVR.CCK\Scripts\Components\CVRLTCGIAdapter.cs(107,60): error CS1061: 'LTCGI_UdonAdapter' does not contain a definition for 'DEBUG_ReverseUnityLightmapST' and no accessible extension method 'DEBUG_ReverseUnityLightmapST' accepting a first argument of type 'LTCGI_UdonAdapter' could be found (are you missing a using directive or an assembly reference?)`

**Comment by kafeijao** [comment]
Version: CCK 4.0.0 preview 11 

Targeting the main avatar animator in a `CVRAnimatorDriver` doesn't work. It calls the OnValidate somewhere during build/upload at a point where the main animator was removed or something. This causes the type of the param to be -1, which is invalid and ignored by the game client

**Comment by kafeijao** [comment]
Version: CCK 4.0.0 preview 11

If a validation error gets added (eg. shader compile error) after we already trigger a validation, the build/upload will fail saying validation error, but it won't show on the validation window until we manually re-refresh it.

Suggestion: Re-trigger the validation when the upload/build fails due a validation error (at least if there are no validation errors on the current window)

**Comment by NotAKidoS** [comment]
Version: CCK 4.0.0 preview 11

The CCKTestModeActivafor object is currently being added to any opened scene. Ideally, this object would only be added to a scene when clicking the Enter Test Mode option.

Alternatively, this object can potentially be removed and replaced by the CVRAssetInfo script, as it is already running in-editor for the build panel to track it (so we are already in every scene without adding anything new).

**Comment by Momofier** [comment]
Version: CCK 4.0.0 preview 11
When Clicking a Different Tab in the Control Panel  while Uploading it causes the Uploader to Temporarily break 
Can easily be fixed by Dismissing and then Retrying.

**Comment by VoyVivika** [comment]
CCK 4.0.0 preview 11
"Potential prefab depth light(s) detected" Select All button selects the component itself and not the GameObject it's on.

**Comment by VoyVivika** [comment]
CCK 4.0.0 preview 11
Portal Panorama takes picture from spawn area and doesn't allow for a more ideal preview location (an area of interest more generally representative of the world)

**Comment by Hobohan** [comment]
Version: CCK 4.0.0 preview 11

Imported new poi everything exploded

`Assets\_PoiyomiShaders\Scripts\ThryEditor\External\Editor\AbiAutoLock.cs(6,7): error CS0246: The type or namespace name 'ABI' could not be found (are you missing a using directive or an assembly reference?)`

no idea if this is my fault if so feel free to say so lol.

**Comment by NotAKidoS** [comment]
oopsie that went missing when i killed the legacy build panel

**Comment by NotAKidoS** [comment]
nevermind it is still there 🤔 
<img width="989" height="694" alt="Image" src="https://github.com/user-attachments/assets/3cab806b-1d10-4d2a-8618-3e2916f9b262" />

**Comment by Hobohan** [comment]
Went back to older version of poi currently working is 9.3.43 but 9.3.49 is def a no go.

Thanks Kiddo

**Comment by NotAKidoS** [comment]
This incompatibility with the latest poiyomi releases is due to changes on their side and there is nothing we can do *at this moment* to address it.

There is now an assembly definition used for the thirdparty hooks included with poiyomi which makes their scripts no longer able to find the CCK. All of our scripts are in Assembly-CSharp and you cannot directly depend on that from a custom assembly. 
<img width="420" height="127" alt="Image" src="https://github.com/user-attachments/assets/16c66d3f-64b7-41c4-8039-1b61ea977401" />

Liltoon works around this by using reflection which Thry could also do to maintain compatibility:
https://github.com/lilxyzw/lilToon/blob/master/Assets/lilToon/External/Editor/ChilloutVRModule.cs#L20-L27

We have an open issue to move ourselves to a proper assembly, but as of right now we cannot act on it. Some other tasks must be done first before we can attempt that (as we may need to restructure the client & need to figure out migrating existing projects). https://github.com/ChilloutVR-Team/ChilloutVR-Issues/issues/895

Snippet from the initial CCK4 release notes:

## Legacy Compatibility
- Legacy build events are still fired to maintain compatibility with existing tools (Callback order -1)
  - Ex: [Poiyomi](<https://github.com/poiyomi/PoiyomiToonShader/blob/52b73edcb11d194ae68084da06a2833248326237/_PoiyomiShaders/Scripts/ThryEditor/External/Editor/AbiAutoAnchor.cs#L14>), [Liltoon](<https://github.com/lilxyzw/lilToon/blob/e0b739549b87263c007915bc200e0837fa156445/Assets/lilToon/External/Editor/ChilloutVRModule.cs#L20-L27>), & [Zettais BakeBlenshapes Tool](<https://github.com/ZettaiVR/UnityTools/blob/418e9834c939a0743cbb6eb6a9babd3e39fba63a/BakeBlendshapes/Editor/BakeBlendshapesBuildIntegration.cs#L270-L271>)
- However, scripts relying on PlayMode state changes for cleanup may need updates
    - Ex: [UnusedBoneRefCleaner](<https://github.com/NotAKidoS/UnusedBoneRefCleaner/blob/f62b1205e51b26de6a794eb094926fc15358f8e4/Editor/CCK_UnusedBoneRefCleaner_BuildHook.cs#L34-L42>) & [Zettais RemoveUnneededBones Tool](<https://github.com/ZettaiVR/UnityTools/blob/418e9834c939a0743cbb6eb6a9babd3e39fba63a/RemoveUnneededBones/Editor/RemoveUnneededBonesEditor.cs#L123>)
- **World building now uses a duplicate scene for non-destructive preprocessing**
  - Ex: Fixes [CVRLuaTools](<https://github.com/NotAKidoS/CVRLuaTools/blob/e266cdb1cbc25026478e67bbaf7a4d975926457e/Editor/CCKBuildEventListener.cs#L27-L36>) not being able to destroy wrapper components on world build without modifying the source scene
  - Updated: [CVRLuaTools CCKBuildEventListener.cs](<https://github.com/NotAKidoS/CVRLuaTools/blob/322bacef0fa848e49a2053c283bae22a49f6115e/Editor/CCKBuildEventListener.cs#L10-L24>)

**Note; We do not plan to remove these old build events anytime soon, if ever, but we recommend using the new build processers if able. We know some thirdparty packages are only able to hook the CCK via reflection right now & we do plan on solving that in the future.**

**Comment by art0007i** [comment]
Version: CCK 4.0.0 preview 11

If you have multiple props with the same gameobject name, only one will show up in the cck control panel 

<img width="684" height="300" alt="Image" src="https://github.com/user-attachments/assets/6a9870bb-ab2c-4e0b-9d5d-b1dfb937f2c7" />

**Comment by hanzcvr** [comment]
When using magica mesh cloth one can provide a map texture (based on the cloth mesh's uv layout) to show what parts of the mesh should move and which should not. This requires read/write on the map texture to function. If possible, exclude textures in this form of use from the rw validation of textures.

**Comment by Malthbern** [comment]
The pano appears to capture the scene with real time lighting despite lights being both set to and being baked.

<img width="2218" height="983" alt="Image" src="https://github.com/user-attachments/assets/e041c333-0f58-4804-980c-d9e9c34ed7c1" />
<img width="2560" height="1362" alt="Image" src="https://github.com/user-attachments/assets/696f81e2-13cc-4268-8bb1-d76d40750dc4" />
<img width="2560" height="1359" alt="Image" src="https://github.com/user-attachments/assets/660a8411-69b6-4188-9aa7-e9e8709c76b2" />

**Comment by Momofier** [comment]
Multi-Object Editing on Components Would be Very Nice!! ;D 

It's really annoying when working on many Objects at once for me to have to Deselect an object just to put the same value 18 times. The Current way is entirely monotonous to work with.  It would make my life 10000 times easier. I make Prefabs for my Objects, and I'm Sure I'm not the only one that does this. 

This would also just increase efficiency with making Props and Worlds. 

<img width="594" height="563" alt="Image" src="https://github.com/user-attachments/assets/1051df65-07ec-4002-b6e2-e3567636416c" />

**Comment by hanzcvr** [comment]
CCKPlayModeActivator will upload with worlds. Maybe when you instantiate it in the scene, set its tag as "Editor Only" to prevent `The referenced script on this Behaviour (Game Object 'CCKPlayModeActivator') is missing!` messages in the log.

(Ignore the fact I have it turned off for now, doing cursed things with unity 2022).

<img width="324" height="222" alt="Image" src="https://github.com/user-attachments/assets/bbbd9e8d-a8e4-401a-90c9-cf534a176fcb" />

Following patch will generate the object with the tag set to EditorOnly directly. Tested against `CCK_4.0.0_Preview.17.unitypackage`
```diff
diff --git a/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs b/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
index a2a2937..6249b66 100755
--- a/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
+++ b/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
@@ -139,6 +139,7 @@ namespace CVR.CCKEditor.TestMode
                 if (!activatorExists)
                 {
                     GameObject activatorObject = new("CCKPlayModeActivator");
+                    activatorObject.tag = "EditorOnly";
                     activatorObject.AddComponent<CCKTestModeActivator>();
                     SceneManager.MoveGameObjectToScene(activatorObject, scene);
                     Debug.Log($"[CCK] Created CCKPlayModeActivator in scene: {scene.name}");
```

**Comment by hanzcvr** [comment]
`CCK_4.0.0_Preview.19.unitypackage`'s default AvatarAnimator contains a float parameter called `meow-x` with value 0. I suspect some debug stuff made it into prerelease lol.

**Comment by NotAKidoS** [comment]
meow

**Comment by NotAKidoS** [comment]
This seems to not exist in latest preview. I probably built that prior preview package without clearing staged changes to the default animator when testing this specific fix:
> Fixed an issue where the missing parameter error element on the AAS menu entries would falsly state the Color, Joystick, or Input parameters did not exist in the base controller

My bad.
<img width="412" height="631" alt="Image" src="https://github.com/user-attachments/assets/150b11fb-91bf-491f-9f9a-9ec47194a34c" />

**Comment by hanzcvr** [comment]
Guess I'm a bit out of date. Minor issue, but figured it was worth bringing up.
On another (but slightly related) note. I think the preview builds should be more accessible.
Especially at this moment (discord ID slop), not everyone can or wants to be on discord, or a specific server.

**Comment by Momofier** [comment]
The CCK Currently prevents Unity from going to iOS Build. (Tested on Preview 19 and 21)
This Interferes with VRC's SDK Currently. Keeping it from uploading to iOS. 

This Affects any shared Projects where both the CVRCCK and VRCSDK are included.

**Comment by Momofier** [comment]
<img width="192" height="189" alt="Image" src="https://github.com/user-attachments/assets/08ee8b25-8208-4c8b-b7fe-aa6e83ebdc02" />
I think it would also be cool to have a Checkbox dropdown like how it is in VRC for those that want to push their updates(If optimized enough) to both Quest and PC. Yes, VRC does this, but I think if we plan on having other build targets in the future this is a great way to streamline the operation.

**Comment by NotAKidoS** [comment]
> Guess I'm a bit out of date. Minor issue, but figured it was worth bringing up.
> On another (but slightly related) note. I think the preview builds should be more accessible.
> Especially at this moment (discord ID slop), not everyone can or wants to be on discord, or a specific server.


Latest preview is now available on our docs: https://docs.chilloutvr.net/cck/setup/

I don't have the ability to deploy these myself, so releases on our docs may lag behind during back-to-back preview updates, but a full 4.0.0 release is likely sooner rather than later.

**Comment by NotAKidoS** [comment]
> CCKPlayModeActivator will upload with worlds. Maybe when you instantiate it in the scene, set its tag as "Editor Only" to prevent `The referenced script on this Behaviour (Game Object 'CCKPlayModeActivator') is missing!` messages in the log.
> 
> (Ignore the fact I have it turned off for now, doing cursed things with unity 2022).
> 
> <img width="324" height="222" alt="Image" src="https://github.com/user-attachments/assets/bbbd9e8d-a8e4-401a-90c9-cf534a176fcb" />
> 
> Following patch will generate the object with the tag set to EditorOnly directly. Tested against `CCK_4.0.0_Preview.17.unitypackage`
> ```diff
> diff --git a/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs b/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
> index a2a2937..6249b66 100755
> --- a/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
> +++ b/Scripts/Editor/TestMode/CCKTestModeManager.Internal.cs
> @@ -139,6 +139,7 @@ namespace CVR.CCKEditor.TestMode
>                  if (!activatorExists)
>                  {
>                      GameObject activatorObject = new("CCKPlayModeActivator");
> +                    activatorObject.tag = "EditorOnly";
>                      activatorObject.AddComponent<CCKTestModeActivator>();
>                      SceneManager.MoveGameObjectToScene(activatorObject, scene);
>                      Debug.Log($"[CCK] Created CCKPlayModeActivator in scene: {scene.name}");
> ```

I did not see this until now. I've been meaning to experiment with making CVRAssetInfo the playmode activator as it's always there, but I could probably do this as well and hide it in the scene to not clutter things.

(i wish unity had apis to do this stuff without jank in the first place...)

**Comment by hanzcvr** [comment]
> Latest preview is now available on our docs: https://docs.chilloutvr.net/cck/setup/
> 
> I don't have the ability to deploy these myself, so releases on our docs may lag behind during back-to-back preview updates, but a full 4.0.0 release is likely sooner rather than later.

Nice. I noticed the stable release has NAK.Contacts whitelisted. I assume those will be included in an upcoming CCK 4.0 release? Also, the new 181 release notes mentions a lot more 'default contacts' beyond the mouth/index/grab, but as far as I can see doesn't mention the index pointer itself. As many pieces of content may be looking for 'index' specifically, will that remain part of the 'default pointers' and should creators add it?

> I did not see this until now. I've been meaning to experiment with making CVRAssetInfo the playmode activator as it's always there, but I could probably do this as well and hide it in the scene to not clutter things.
> 
> (i wish unity had apis to do this stuff without jank in the first place...)

Yeah its jank af, but I guess it works.

**Comment by NotAKidoS** [comment]
The "index" pointer type is still there, I just forgot it when making the changelog.

The NAK.Contacts components are currently whitelisted so the filtering system does not remove them, since they are now created internally at load to handle trigger/pointers collision events. These will likely be unwhitelisted later alongside a v2 triggers and pointers component set. This initial rework was focused on moving the existing implementation into the new system so it is compatible with whatever replaces it, avoiding a Magica Cloth 1/2 situation where old and new systems coexist without interacting.

I don't have a timeline for when I will be able to do that though. I was initially planning for an intermediary update to pointers/triggers to expose at least some of the new functionality and remove collider jank on cck side, but I had to pause that due to complexity and lack of time.

**Comment by hanzcvr** [comment]
Noted, and yeah I checked the kyle robot avatar with unity explorer. Should creators *not* use NAK.Contacts at this moment, then? or will there maybe be a Contacts->Pointer/Trigger v2 conversion once that happens? Or is using them okay if the creator is willing to convert later?

**Comment by NotAKidoS** [comment]
> Noted, and yeah I checked the kyle robot avatar with unity explorer. Should creators _not_ use NAK.Contacts at this moment, then? or will there maybe be a Contacts->Pointer/Trigger v2 conversion once that happens? Or is using them okay if the creator is willing to convert later?

There is no harm in fucking around with it while it exists, but there likely won't be any conversion for something that isn't publicly supported.

**Comment by NotAKidoS** [comment]
Closing as CCK v4.0.0 has released. v3.16.4 will be available through the docs as well for a little while to allow a transition period.

Any remaining issues or feature requests should be spun into their own posts now for tracking purposes.

https://docs.chilloutvr.net/cck/setup/

**Comment by hanzcvr** [comment]
[Changelog](https://docs.chilloutvr.net/cck/changelogs/preview-4.0.0/) still points to this thread at the very end, btw.

**Comment by NotAKidoS** [comment]
The docs needs a couple of things fixed/documented relating to CCK4. Will be trying to get to that sometime soon.
